Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -31,14 +31,14 @@ steps:
       ls -lrt
   displayName: 'Download FoD JAR'
 
-- task: Bash@3
-  inputs:
-     targetType: 'inline'
-     script: |
-         java -jar FodUpload.jar -ac $(FOD-API-KEY) $(FOD-SECRET) -rid 114186 -purl "https://emea.fortify.com/" -apiurl "https://api.emea.fortify.com/" -z develop.zip -ep 2 -rp 2 -pp 1 -apf -I 1
-                status=$?
-                echo $status
-  displayName: 'FOD Code SCAN'             
+# - task: Bash@3
+#   inputs:
+#      targetType: 'inline'
+#      script: |
+#          java -jar FodUpload.jar -ac $(FOD-API-KEY) $(FOD-SECRET) -rid 114186 -purl "https://emea.fortify.com/" -apiurl "https://api.emea.fortify.com/" -z develop.zip -ep 2 -rp 2 -pp 1 -apf -I 1
+#                 status=$?
+#                 echo $status
+#   displayName: 'FOD Code SCAN'             
 
 - task: Bash@3
   inputs:
@@ -60,18 +60,20 @@ steps:
              echo "HIGH = $HIGH"
              if [ $CRITICAL -gt 5 ]
              then
-               echo "Failing task because number of critical issues are greater than 5"
+               echo "##[warning]Failing task because number of critical issues are greater than 5"
                echo $applicationname
-               curl -H 'Content-Type: application/json' -d '{"text": "Pipeline failed because number of critical issues in FoD SAST are greater than 5 for '$applicationname'"}' $(teams_webhook)
-               exit 1
+               curl -H 'Content-Type: application/json' -d '{"text": "Pipeline had warnings because number of critical issues in FoD SAST are greater than 5 for '$applicationname'"}' $(teams_webhook)
+               #exit 1
              elif [ $HIGH -gt 10 ]
              then
-               echo "Failing task because number of high issues are greater than 10"
-               exit 1
+               echo "##[warning]Failing task because number of high issues are greater than 10"
+               curl -H 'Content-Type: application/json' -d '{"text": "Pipeline had warnings because number of high issues in FoD SAST are greater than 10 for '$applicationname'"}' $(teams_webhook)
+               #exit 1
              elif [ $SUM -gt 50 ]
              then
-               echo "Failing task because number of total issues are greater than 50"
-               exit 1
+               echo "##[warning]Failing task because number of total issues are greater than 50"
+               curl -H 'Content-Type: application/json' -d '{"text": "Pipeline had warnings because total number of issues in FoD SAST are greater than 50 for '$applicationname'"}' $(teams_webhook)
+               #exit 1
              else
                echo "PASSED"
              fi
